version: '2'

services:
    db:
        container_name: api_server_db
        image: mysql:5.6
        volumes:
            - ${MYSQL_DATA_DIR}:/var/lib/mysql
            - ${MYSQL_LOGS_DIR}:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"

    redis:
        container_name: api_server_redis
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - ${REDIS_DATA_DIR}:/data

    php:
        container_name: api_server_php
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/html
        links:
            - redis
        depends_on:
            - db
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
            XDEBUG: ${XDEBUG}
            XDEBUG_CONFIG: ${XDEBUG_CONFIG}
            SYMFONY_ENV: ${SYMFONY_ENV}
            SYMFONY_DEBUG: ${SYMFONY_DEBUG}
            SYMFONY_LOG: ${SYMFONY_LOG}

    nginx:
        container_name: api_server_nginx
        build: docker/nginx
        volumes_from:
            - php
        volumes:
            - .${NGINX_LOGS_DIR}:/var/log/nginx
        ports:
            - "80:80"

    rabbit:
        container_name: api_server_rabbit
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        volumes:
            - ${RABBITMQ_DATA_DIR}:/var/lib/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"

    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ${ELK_LOGS_DIR}:/etc/logstash
            - ${ELK_LOGS_PATTERNS_DIR}:/opt/logstash/patterns
            - ${ELASTICSEARCH_DATA_DIR}:/var/lib/elasticsearch
        volumes_from:
            - php
            - nginx
        container_name: api_server_elk
