version: '2'

services:
    db:
        container_name: api_server_db
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"

    redis:
        container_name: api_server_redis
        image: redis:alpine
        ports:
            - "6379:6379"

    php:
        container_name: api_server_php
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - redis

    nginx:
        container_name: api_server_nginx
        build: nginx
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - 80:80

    rabbit:
        container_name: api_server_rabbit
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        volumes:
            - ./.data/rabbitmq/:/var/lib/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"

    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
            - ./.data/elasticsearch:/var/lib/elasticsearch
        volumes_from:
            - php
            - nginx
        container_name: api_server_elk
