#index:
#    path: /
#    defaults: { _controller: 'App\Controller\HelloController::index' }

controllers:
  prefix: /api/v1
  resource: ../src/Controller/

api_entrypoint:
  path: /api/v1
  methods: [GET]

api_doc:
  path: /api/v1
  methods: [GET]

api_jsonld_context:
  path: /api/v1
