parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: UTF8
#        With Symfony 3.3, remove the `resolve:` prefix
#        url: '%env(resolve:DATABASE_URL)%'
        url: 'mysql://root:root@127.0.0.1:3306/labellead'

#        default_connection: default
#        connections:
#            default:
#                driver: 'pdo_mysql'
#                host: '%env(DB_HOST)%'
#                port: '%env(DB_PORT)%'
#                dbname: '%env(DB_NAME)%'
#                user: '%env(DB_USER)%'
#                password: '%env(DB_PASSWORD)%'
#                charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
