security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_LAWYER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email


    firewalls:
        login:
            pattern:  ^/api/v1/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            json_login:
                check_path: /api/v1/login
#                username_parameter: username
#                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        main:
            pattern: ^/api
            provider: fos_userbundle
            stateless: true
            anonymous: true
            lexik_jwt: ~
#            guard:
#                authenticators:
#                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api/v1/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/profile, roles: [ ROLE_USER ] }
        - { path: ^/api/v1/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/v1, roles: [ ROLE_USER ] }